### ISSUE TITLE
Add Android e2e tests (Detox)

### ISSUE THREAD

**Issue by jasonhealy** [uport-project/kancha-ui#49]
Currently iOS is set up for e2e tests using Detox. Issues were experienced getting Android to work but the issue is being tracked on WIX here.

https://github.com/wix/Detox/issues/1450

**Comment by shubhnik** [comment]
@jasonhealy Can you please revert back on the [issue thread](https://github.com/wix/Detox/issues/1450) if you managed to solve this issue. It will be very helpful.
